In [2]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1-dimensional array
a = np.array([1, 2, 3, 4, 5])
print("1-dimensional array:")
print(a)

# Step 3: Create a 2-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2-dimensional array:")
print(b)

# Step 4: Create an array of zeros
c = np.zeros((3, 4))
print("\nArray of zeros:")
print(c)

# Step 5: Create an array of ones
d = np.ones((2, 2))
print("\nArray of ones:")
print(d)

# Step 6: Perform mathematical operations on arrays
# Adding two arrays
e = np.array([1, 2, 3])
f = np.array([4, 5, 6])
result_add = e + f
print("\nResult of adding two arrays:")
print(result_add)

# Multiplying two arrays
g = np.array([[1, 2], [3, 4]])
h = np.array([[5, 6], [7, 8]])
result_multiply = g * h
print("\nResult of multiplying two arrays:")
print(result_multiply)

# Matrix multiplication
i = np.dot(g, h)
print("\nResult of matrix multiplication:")
print(i)


1-dimensional array:
[1 2 3 4 5]

2-dimensional array:
[[1 2 3]
 [4 5 6]]

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of ones:
[[1. 1.]
 [1. 1.]]

Result of adding two arrays:
[5 7 9]

Result of multiplying two arrays:
[[ 5 12]
 [21 32]]

Result of matrix multiplication:
[[19 22]
 [43 50]]
